import '@/styles/global.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import { Toaster } from '@/components/ui';
import { ProgressBar } from '@/components';

const openSans = Open_Sans({
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={openSans.className}>
      <body>
        {children}
        <Toaster />
        <ProgressBar />
      </body>
    </html>
  );
}
